main.py
from flask import Flask
from routes.home import home_route
from routes.board import board_route

app = Flask(__name__)

app.register_blueprint(home_route)
app.register_blueprint(board_route, url_prefix='/board')

app.run(debug=True)

routes/board.py
from flask import Blueprint, render_template
from src.board import Board
from src.player import Player
from src.ia import IA
from time import sleep

board_route = Blueprint('board', __name__)

def __toString(board:list[list[str]]) -> str:
    s = ''

    for b in board:
        s += ','.join(b) + ';'
    
    s = s[:-1]

    return s

def __toList(string: str) -> list[list[str]]:
    board = []

    string = string.split(';')
    for s in string:
        board.append(s.split(','))

    return board

def get_board() -> list[list[str]]:
    return __board.get_board()

def set_board(new_board:list[list[str]]):
    __board.set_board(new_board)

def playing_ia() -> list[list[str]]:
    __ia.fazer_movimento()

__board = Board()
__board.iniciar_jogo()
__jogador = IA(__board, is_player=True)
__ia = IA(__board, is_player=False)


@board_route.route('/')
def render_board():
    board_str = __toString(get_board())
    return render_template('board.html', board=get_board())

@board_route.route('/', methods=['POST'])
def update_board():
    return render_template('board.html', board=get_board())

routes/home.py
from flask import Blueprint, render_template
from src.board import Board
from src.player import Player

home_route = Blueprint('home', __name__)

@home_route.route('/')
def home():
    return render_template('index.html')

src/app.py
from src.board import Board
from src.player import Player
from src.ia import IA

def get_board() -> list[list[str]]:
    return board.get_board()

def set_board(new_board:list[list[str]]):
    board.set_board(new_board)

def playing_ia() -> list[list[str]]:
    ia.fazer_movimento()

board = Board()
board.iniciar_jogo()
jogador = Player(board, is_player=True)
ia = IA(board)

templates/board.html
{% for i in range(8) %} <!-- Cria as linhas -->
    <div class="row">
        {% for j in range(8) %} <!-- Cria as Colunas -->
            {% if i%2 == 0 %} <!-- se linha par, começa com branco -->
                <div class="cell color-{{ j%2 }}" id="cell-{{ i }}-{{ j }}">
                
                    {% if 'P' in board[i][j] %}
                        <img src="{{ url_for('static', filename='assets/peça-1.png') }}" alt="">
                    {% elif 'B' in board[i][j] %}
                        <img src="{{ url_for('static', filename='assets/peça-0.png') }}" alt="">
                    {% endif %}

                </div>
            {% else %} <!-- se linha impar, começa com branco -->
                <div class="cell color-{{ (j+1)%2 }}" id="cell-{{ i }}-{{ j }}">
                    {% if 'P' in board[i][j] %}
                        <img src="{{ url_for('static', filename='assets/peça-1.png') }}" alt="">
                    {% elif 'B' in board[i][j] %}
                        <img src="{{ url_for('static', filename='assets/peça-0.png') }}" alt="">
                    {% endif %}
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endfor %}

templates/index.html
<!doctype html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Dama</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/board.css') }}">
  </head>
  <body class="color-1">
    <div class="container color-0" id="board" 
    c-container="{{ url_for('board.render_board') }}"
    
    c-reload-container="true"
    ></div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename='js/cru.js')  }}"></script>
  </body>
</html>